name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: '.commitlintrc.json'

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Lint & format
        run: |
          black --check .
          isort --check-only .
          flake8 app
      - name: Run tests
        run: pytest -q

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      - name: Terraform init
        working-directory: infra/terraform
        run: terraform init -input=false
      - name: Terraform fmt (check)
        working-directory: infra/terraform
        run: terraform fmt -check -recursive
      - name: Terraform validate
        working-directory: infra/terraform
        run: terraform validate
      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Run tflint
        working-directory: infra/terraform
        run: tflint
